CREATE DATABASE QLKS
USE QLKS


CREATE TABLE NHANVIEN(
	MANV CHAR(4) NOT NULL PRIMARY KEY,
	NHOTEN VARCHAR(50) NOT NULL,
	NSDT CHAR(10) NOT NULL,
	NGIOITINH VARCHAR(4) NOT NULL,
	NDIACHI VARCHAR(100) NOT NULL,
	NEMAIL VARCHAR(50) NOT NULL,
	POSITION TINYINT NOT NULL,
	CHUCVU VARCHAR(50) NOT NULL,
	LUONG MONEY NOT NULL,
	NCCCD VARCHAR(10) NOT NULL, /*NEW*/
	NNGSINH DATETIME NOT NULL /*NEW*/
)

CREATE TABLE LOAIPHONG(
	MALOAIPHG CHAR(4) NOT NULL PRIMARY KEY,
	TENLOAIPHG VARCHAR(10) NOT NULL,
	GIADEM MONEY NOT NULL,
	SUCCHUA TINYINT NOT NULL, /*NEW*/
	SOGIUONG TINYINT NOT NULL /*NEW*/
	/*XOA COT:
	MAXTRGTHANH 
	MAXTHIEUNHI
	MAXSOSINH*/
)

CREATE TABLE KHACHHANG(
	MAKH CHAR(4) NOT NULL PRIMARY KEY,
	KHOTEN VARCHAR(50) NOT NULL,
	KSDT CHAR(10) NOT NULL,
	QUOCTICH VARCHAR(50) NOT NULL,
	KGIOITINH VARCHAR(4) NOT NULL,
	KNGSINH DATETIME NOT NULL,
	KCCCD CHAR(12) NOT NULL,
	KDIACHI VARCHAR(100) NOT NULL,
	KEMAIL VARCHAR(50) NOT NULL, /*NEW*/
	/*XOA COT:
	CHECKIN
	CHECKOUT
	CHEKOUT
	ROOMID*/
)

CREATE TABLE HOADON(
	MAHD CHAR(7) NOT NULL PRIMARY KEY,
	MAKH CHAR(4) NOT NULL FOREIGN KEY REFERENCES KHACHHANG(MAKH),
	MANV CHAR(4) NOT NULL FOREIGN KEY REFERENCES NHANVIEN(MANV),
	TONGTIEN MONEY NOT NULL,
	PHGTHUC VARCHAR(10) NOT NULL,
	NGTHANHTOAN SMALLDATETIME NOT NULL,
	NGXUATHD SMALLDATETIME NOT NULL,
)

CREATE TABLE PHONG(
	MAPHG CHAR(4) NOT NULL PRIMARY KEY,
	MALOAIPHG CHAR(4) NOT NULL FOREIGN KEY REFERENCES LOAIPHONG(MALOAIPHG),
	TRANGTHAI VARCHAR(10) NOT NULL,
	TANG TINYINT NOT NULL,
	GHICHU TEXT NOT NULL
	/*XOA COT MAKS*/
)

CREATE TABLE CTPHG(
	MAPHG CHAR(4) NOT NULL FOREIGN KEY REFERENCES PHONG(MAPHG),
	MAHD CHAR(7) NOT NULL FOREIGN KEY REFERENCES HOADON(MAHD),
	NGNHANPHG DATETIME NOT NULL,
	NGTRPHG DATETIME NOT NULL,
	TIENDATPHG MONEY NOT NULL
)

CREATE TABLE DICHVU(
	MADV CHAR(4) NOT NULL PRIMARY KEY,
	TENDV VARCHAR(20) NOT NULL,
	GIADV MONEY NOT NULL
)

CREATE TABLE CTDV(
	MAHD CHAR(7) NOT NULL FOREIGN KEY REFERENCES HOADON(MAHD),
	MADV CHAR(4) NOT NULL FOREIGN KEY REFERENCES DICHVU(MADV),
	SOLUONG INT NOT NULL,
	THOIGIANSD SMALLDATETIME NOT NULL
)