CREATE FUNCTION TONGTIENPHONGTHANG (@NAM INT, @THANG INT)
RETURNS DECIMAL(19,4)
AS
BEGIN
	DECLARE @TONGTIENPHG DECIMAL(19,4), @TIENPHG DECIMAL(19,4)
	DECLARE CUR CURSOR FOR
		SELECT CAST(TIENDATPHG AS DECIMAL(19,4))
		FROM CTPHG, HOADON
		WHERE CTPHG.MAHD = HOADON.MAHD
		AND YEAR(HOADON.NGTHANHTOAN) = @NAM AND MONTH(HOADON.NGTHANHTOAN) = @THANG

	SET @TONGTIENPHG = 0

	OPEN CUR 
	FETCH NEXT FROM CUR
		INTO @TIENPHG

	WHILE @@FETCH_STATUS = 0
	BEGIN
		SET @TONGTIENPHG = @TONGTIENPHG + @TIENPHG * 1.1
		FETCH NEXT FROM CUR
			INTO @TIENPHG
	END

	CLOSE CUR
	DEALLOCATE CUR

	RETURN @TONGTIENPHG
END
GO

CREATE FUNCTION TONGTIENDICHVUTHANG (@NAM INT, @THANG INT)
RETURNS DECIMAL(19,4)
AS
BEGIN
	DECLARE @TONGTIENDICHVU DECIMAL(19,4), @GIADV DECIMAL(19,4), @SOLUONG INT
	DECLARE CUR CURSOR FOR
		SELECT CAST(GIADV AS DECIMAL(19,4)), SOLUONG
		FROM CTDV, HOADON, DICHVU
		WHERE CTDV.MAHD = HOADON.MAHD AND CTDV.MADV = DICHVU.MADV
		AND YEAR(HOADON.NGTHANHTOAN) = @NAM AND MONTH(HOADON.NGTHANHTOAN) = @THANG

	SET @TONGTIENDICHVU = 0

	OPEN CUR 
	FETCH NEXT FROM CUR
		INTO @GIADV, @SOLUONG

	WHILE @@FETCH_STATUS = 0
	BEGIN
		SET @TONGTIENDICHVU = @TONGTIENDICHVU + @GIADV * @SOLUONG * 1.1
		FETCH NEXT FROM CUR
			INTO @GIADV, @SOLUONG
	END

	CLOSE CUR
	DEALLOCATE CUR

	RETURN @TONGTIENDICHVU
END
GO

CREATE FUNCTION TONGTIENLUONGTHANG ()
RETURNS DECIMAL(19,4)
AS
BEGIN
	DECLARE @TONGTIENLUONG DECIMAL(19,4)
	SELECT @TONGTIENLUONG = SUM(LUONG)
							FROM NHANVIEN
							WHERE HOATDONG = 1

	IF(@TONGTIENLUONG IS NULL)
		SET @TONGTIENLUONG = 0

	RETURN @TONGTIENLUONG
END	
GO

CREATE PROCEDURE DOANHTHUTUNGTHANG @NAM INT
AS
BEGIN
	CREATE TABLE #DOANHTHU(
		THANG INT,
		THUNHAP DECIMAL(19,4),
		CHIPHI DECIMAL(19,4),
		DOANHTHU DECIMAL(19,4)
		)
	DECLARE @PHONG DECIMAL(19,4), @DICHVU DECIMAL(19,4), @LUONG DECIMAL(19,4), @DOANHTHU DECIMAL(19,4), @THANG INT

	SET @THANG = 1
	SET @LUONG = DBO.TONGTIENLUONGTHANG()

	WHILE (@THANG <= 12)
	BEGIN
		SET @PHONG = DBO.TONGTIENPHONGTHANG(@NAM, @THANG)
		SET @DICHVU = DBO.TONGTIENDICHVUTHANG(@NAM, @THANG)
		SET @DOANHTHU = @PHONG + @DICHVU - @LUONG

		INSERT INTO #DOANHTHU VALUES(@THANG, @PHONG + @DICHVU, @LUONG, @DOANHTHU)

		SET @THANG = @THANG + 1
	END
	SELECT * FROM #DOANHTHU
	DROP TABLE #DOANHTHU
END
GO

CREATE PROCEDURE CHITIETDOANHTHUTUNGTHANG @NAM INT
AS
BEGIN
	CREATE TABLE #DOANHTHU(
		THANG INT,
		PHONG DECIMAL(19,4),
		DICHVU DECIMAL(19,4),
		LUONG DECIMAL(19,4),
		DOANHTHU DECIMAL(19,4)
		)
	DECLARE @PHONG DECIMAL(19,4), @DICHVU DECIMAL(19,4), @LUONG DECIMAL(19,4), @DOANHTHU DECIMAL(19,4), @THANG INT

	SET @THANG = 1
	SET @LUONG = DBO.TONGTIENLUONGTHANG()

	WHILE (@THANG <= 12)
	BEGIN
		SET @PHONG = DBO.TONGTIENPHONGTHANG(@NAM, @THANG)
		SET @DICHVU = DBO.TONGTIENDICHVUTHANG(@NAM, @THANG)
		SET @DOANHTHU = @PHONG + @DICHVU - @LUONG

		INSERT INTO #DOANHTHU VALUES(@THANG, @PHONG + @DICHVU, @LUONG, @DOANHTHU)

		SET @THANG = @THANG + 1
	END
	SELECT * FROM #DOANHTHU
	DROP TABLE #DOANHTHU
END