PRINT DBO.TONGTIENPHONGTHANG(2024,1)
PRINT DBO.TONGTIENDICHVUTHANG(2024,1)
PRINT DBO.TONGTIENLUONGTHANG()
PRINT DBO.TONGDOANHTHUTHANG(2024,1)

SELECT DBO.TONGTIENPHONGTHANG(2024,1) AS 'PHONG', 
	DBO.TONGTIENDICHVUTHANG(2024,1) AS 'DICHVU', 
	DBO.TONGTIENLUONGTHANG() AS 'LUONG', 
	DBO.TONGDOANHTHUTHANG(2024,1) AS 'DOANHTHU'

EXEC DOANHTHUTUNGTHANG @NAM = 2024